rancher/machine

libmachine/ssh/client.go

This PR is completely same as the PR I created for upstream docker/machine.
The detail issue resolved by this PR can be seen in https://github.com/docker/machine/issues/4549 .
This PR will resolve rancher-server's issue https://github.com/rancher/rancher/issues/14933

Return error of command exec in SSH NativeClient

---

drivers/vmwarevsphere/vsphere.go

Part of rancher/rancher#15817
Added params:
- `vmwarevsphere-vapp-ipprotocol`
- `vmwarevsphere-vapp-ipallocationpolicy`
- `vmwarevsphere-vapp-transport`
- `vmwarevsphere-vapp-property`

Support vSphere network protocol profiles

---

drivers/amazonec2/region.go

https://github.com/rancher/rancher/issues/18589

Add eu-north-1 to AMIs

---

drivers/amazonec2/region.go

https://github.com/rancher/rancher/issues/20474

Support ap-east-1 and us-gov-east-1

---

drivers/vmwarevsphere/vsphere.go

Problem: Vsphere node deletion entirely relies on the local directory to
ensure uniqueness during node deletion. Pratically, this means the name
is the only unique identifier used. This can be an issue when the
local dir is being modified out of the bounds of docker machine.
Solution: The vsphere driver now uses the ssh key fingerprints of the
keys to ensure the node being deleted is the intended node.
Addresses: https://github.com/rancher/rancher/issues/20971

Improve node vsphere node deletion

---

.gitignore
drivers/vmwarevsphere/vsphere.go

This fixes a couple different bugs
https://github.com/rancher/rancher/issues/24480
https://github.com/rancher/rancher/issues/24416

Move vm/template to Their Own Case

---

drivers/vmwarevsphere/cloudinit.go

The service user we made when merging cloud config yaml would fail in certain situations surrounding the group of the user. defaults for instance of auto-creating a group with the same name of the user would fail to create any user at all if the group already existed. This is just default behavior from useradd so for consistency I've added the groups entry AND the users entry and forced all group creation logic to be off specifying which exact group we will add the new user too.

cloud-config yaml users/groups reworked for more creation consistency

---

drivers/vmwarevsphere/cloudinit.go
drivers/vmwarevsphere/flags.go
drivers/vmwarevsphere/vsphere.go

Addresses https://github.com/rancher/rancher/issues/24758 and https://github.com/rancher/rancher/issues/25073

Fix removal of ISO files from vSphere datastore upon node deletion

---

drivers/vmwarevsphere/create.go

https://github.com/rancher/rancher/issues/25052

pass in host reference properly

---

drivers/vmwarevsphere/create.go
drivers/vmwarevsphere/utils.go

https://github.com/rancher/rancher/issues/20209

adding vapp to clone

---

drivers/azure/azureutil/azureutil.go

This PR adds support for custom images via providing the resource's ARM resource identifier.
More info on ARM resource identifier format: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.batch.models.imagereference.id?view=azure-dotnet#Microsoft_Azure_Management_Batch_Models_ImageReference_Id
Major updates:
- Introduced arm.go + customimage.go to create a unified way of referring to resources that are parsed from ARM resource identifiers
Misc. Updates:
- `getImageReference` now also pulls custom images / gallery images
- Added an error to `CreateVirtualMachine` if a user does not use managed disks with a custom image
Related Issue: https://github.com/rancher/rancher/issues/25342
Dependent on PR: https://github.com/rancher/machine/pull/72

Support custom images

---

libmachine/provision/coreos.go

Cherry Picking @dabeck commit against upstream.

Adding Flatcar Support

---

libmachine/provision/suse.go

Dependent on PR: https://github.com/rancher/install-docker/pull/45
Related Issue: https://github.com/rancher/rancher/issues/25342

Uplift SUSE provisioning

---

libmachine/libmachine.go
libmachine/provision/boot2docker.go
libmachine/provision/debian.go
libmachine/provision/debian_test.go
libmachine/provision/provisioner.go
libmachine/provision/rancheros.go
libmachine/provision/redhat.go
libmachine/provision/redhat_test.go
libmachine/provision/ubuntu_systemd.go
libmachine/provision/ubuntu_systemd_test.go
libmachine/provision/ubuntu_upstart.go
libmachine/provision/ubuntu_upstart_test.go
libmachine/provision/utils.go

https://github.com/rancher/rancher/issues/27414

Overlay2 as the Default Storage Driver

---

drivers/amazonec2/amazonec2.go

Calico CNI doesn't initialize correctly on AWS ec2 instances where the default `rancher-nodes` security group is used.
This is due to the missing port 179 in the security group.
This minor fix  addresses the same.

Additional port for AWS rancher-nodes security group

---

libmachine/provision/coreos.go

https://github.com/rancher/rancher/issues/30326

Enable docker service to avoid socket activation

---

libmachine/provision/photonos.go

This adds support for rancher-machine to provision a Photon OS remote machine.
https://vmware.github.io/photon/

add photon os provisioner

---

libmachine/provision/utils.go

Issue https://github.com/rancher/rancher/issues/31151

Forcing docker restart once auth is configured

---

drivers/vmwarevsphere/vsphere.go
libmachine/drivers/utils.go

https://github.com/rancher/rancher/issues/29286

revert change to wait for ip

---

drivers/vmwarevsphere/create.go

The PR https://github.com/rancher/machine/pull/116 won't take all networks from drivers causing unwanted exits.
This code removes the dependency of template network mapping and instead uses VM reconfiguration logic to add all networks

VM network addition on content library

---

commands/create.go

https://github.com/rancher/rancher/issues/32785
https://github.com/rancher/rancher/issues/33078

gzip+b64 custom install script

---

go.mod
go.sum

Issue: 
- https://github.com/rancher/rancher/issues/27908

Update govmomi version to v0.26.0

---

drivers/amazonec2/amazonec2.go

Issue:
https://github.com/rancher/rancher/issues/34300

Add Typha ports to rancher-nodes security group

---

.drone.yml
Dockerfile.dapper
scripts/build

Add s390x support to rancher/rancher
Part of https://github.com/rancher/rancher/issues/35501

Add s390x arch support

---

libmachine/cert/cert.go
libmachine/ssh/client.go
libmachine/util/util.go

issue: https://github.com/rancher/rancher/issues/28411
add support for utilizing proxy configurations in the running environment when external SSH binary is used

fix ssh behind proxy 

---

drivers/amazonec2/amazonec2.go

Issue: https://github.com/rancher/rancher/issues/24337
When a user provided a security group during EC2 provisioning, rancher-machine would always open ports 22 and 2376 to the world.
After a design discussion, it was determined that rancher-machine should not touch the ports on a user-provided security group. This change not only modifying a security group if it is detected the security group is the `rancher-nodes` security group.
I created a custom security group in AWS that opened ALL ports from my specific IP address.
In order to reproduce the issue, I provisioned an RKE1 cluster in AWS and saw that ports 22 and 2376 were opened to the world, even though Rancher (running from my IP address) already had access to these ports.
To verify that my fix worked, I provisioned an RKE1 cluster …

Stop modifying user-provided security groups

---

.drone.yml

run both fossa analyze and fossa test on drone-publish.

add fossa test

---

.drone.yml

Fix Fossa command and issue regarding duplicate names

Fix fossa commands

---

drivers/amazonec2/amazonec2.go

Issue: https://github.com/rancher/rancher/issues/37561
Port 8443 is required to be open for on downstream RKE2 clusters for the
`rke2-ingress-nginx-controller` webhook, but it was left out of the
rancher-nodes security group. This change adds it.

Add port 8443 to the rancher-nodes security group for AWS

---

libmachine/provision/redhat.go

Issue: https://github.com/rancher/rancher/issues/36526
Rancher was unable to provision nodes when using a RHEL 8.4 AMI. The nodes would either get stuck in `Waiting For API`, or they would encounter port check errors such as `[[network] Host [44.203.82.99] is not able to connect to the following ports: [10.0.12.3:2379]. Please check network policies and firewall rules]`. 
Disable two NetworkManager services (`nm-cloud-setup.service`, `nm-cloud-setup.timer`) which interfered with node networking. A resolution to this issue for custom clusters is documented [here](https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/node-requirements/#oracle-linux-and-rhel-derived-linux-nodes), this PR applies the same fix to nodes provisioned using a node driver. 
I was able to create an EC2 …

[2.6.6] Fix RHEL 8.4 EC2 Node Driver

---

drivers/amazonec2/amazonec2.go

Issue: https://github.com/rancher/rancher/issues/37775
The `TagSpecifications` field was being utilized when creating the `RequestSpotLaunchSpecification` in an attempt to apply tags to all resources created for the instance. However, this field can only be used to tag the spot-instance-request itself, and not the resulting instance. This field accepts the resources `spot-instances-request` and `spot-fleet-request`, but not instance resources such as `instance`, `volume`, or `network-interface`. ([documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_TagSpecification.html))
When creating spot-instances, delay the tagging of the resulting resources until the instance has transitioned into a `running` state. Additionally, enhance the prior tagging implementation to apply …

Apply tags to spot-instances after they have started running

---

drivers/amazonec2/amazonec2.go

Addresses https://github.com/rancher/rancher/issues/37943

Add MetadataOptions on initial create

---

drivers/digitalocean/digitalocean.go

Issue:  https://github.com/rancher/rancher/issues/37510
The `Private Networking` option was available but ignored in digital ocean driver.
Add support to the driver to implement private networking.
I've tested rke1 provisioning so far. I will update when I can test rke2/k3s due to https://github.com/rancher/rancher/issues/38190.
N/A
N/A
N/A

Implemented private ip for digital ocean driver

---

package/Dockerfile

Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

Update SLE version to 15.4.27.8.6

---

drivers/amazonec2/amazonec2.go

Issue: https://github.com/rancher/rancher/issues/38422
This PR resolves an issue wherein relevant log messages were not appearing in the rancher UI when EC2 instances failed to provision.  The error message `Error creating machine: Error in driver during machine creation: MissingParameter: The request must contain the parameter InstanceId, requeuing` was seen in place of any root-cause error (such as invalid block-size or AMI user). This was because the driver was attempting to retrieve a non-existent EC2 instance in the process of cleaning up key-pairs, even if a local key-pair reference was found. Now, if an instance cannot be retrieved the machine will attempt to use the key-pair stored locally in the request. With these changes I was able to observe the following UI messages 
I was …

Graceful deletion of key-pairs

---

commands/create.go

Issue: https://github.com/rancher/rancher/issues/39362
When the vsphere node driver was updated to use `set_hostname` instead of `hostname`, the function used to set this field set it as a list, which would cause setting the hostname to fail.
Append `set_hostname` to cloud-init userdata as a single field.
I tested using a custom built machine image with this fix, and was able to provision over 7 different windows vms with no issue.
N/A
It is required to set `netbios_host_name_compatibility` to false in the `C:\Program Files\Cloudbase Solutions\Cloudbase-Init\conf\cloudbase-init.conf`.
The vms must not have a hostname set prior to powering them on, otherwise the new hostname will not be used until reboot.
Vsphere templates provided to QA upon request.

Add set_hostname as a string for windows vsphere vms

---

.github/workflows/fossa.yaml

update the workflow for FOSSA

---

drivers/amazonec2/region.go

https://github.com/rancher/rancher/issues/44214
Adding new region ca-west-1 as it is currently not supported.

added new region ca-west-1

---

libmachine/drivers/plugin/localbinary/plugin.go

This PR adds support for configuring uid and gid used for running the plugin server.

Enhancement to the plugin server

---

libmachine/drivers/plugin/localbinary/plugin.go
libmachine/drivers/plugin/localbinary/utils.go
libmachine/drivers/plugin/localbinary/utils_windows.go

fix platform issue

---

drivers/azure/azure.go

Issue: https://github.com/rancher/rancher/issues/44944
**Solution:**  Changed the default image value

bump rke azure ubuntu image
