rancher/machine

- drivers/vmwarefusion/fusion_darwin.go
Add nonempty flag to fix share-folder bug.
https://github.com/docker/machine/issues/4481
> Add nonempty flag

- libmachine/provision/rancheros.go
- test/provision/rancheros.bats
To support new version of RancherOS, we need to support following features:
1. Support using overlay2 via --engine-storage-driver flag
2. The versionsURL value should be updated.
3. The isoURL value should be updated, we already do not support any machine-rancheros.iso.
4. No rancherctl, should use ros instead of it.
For issue: https://github.com/rancher/os/issues/2317
> update rancheros provision

- drivers/azure/azure.go
Problem:
The default size for RKE was Standard_A2, despite Standard_D2_v2 being recommended.
Solution:
Make Standard_D2_v2 the default Azure size, and is the same as the default size for AKS.
Issue:
https://github.com/rancher/rancher/issues/15932
> Change Azure default size

- drivers/amazonec2/amazonec2.go
Problem:
Prometheus can not access the node exporter because of the security
group for port 9796
Solution:
Automatically open the port 9796 when creating cluster via ec2 node
driver.
Issue:
https://github.com/rancher/rancher/issues/19187
> fixed the bug that cannot get the metric of nodes

- drivers/azure/azureutil/azureutil.go
Problem:
Disk size is not configurable for VMs with non-managed disks. A user can pass a disk size parameter but it would not be used unless they are using managed disks. Now, all VMs can have their disk size
configured.
Solution:
Using disk size parameter regardless of whether disk is managed or not.
Issue:
https://github.com/rancher/rancher/issues/22074
> Add size to azure non-managed VMs

- drivers/azure/azure.go
Issue: https://github.com/rancher/rancher/issues/21207
Tested against `18.04-LTS` and it worked, `18.04.0-LTS` does not exist. 
And in Azure:
> Bump default azure image to 18.04

- drivers/azure/azure.go
- drivers/azure/azureutil/azureutil.go
Problem:
When deleting a VM that uses managed disks, all related resources besides the VM are left in Azure.
Solution:
Disable unnecessary delete logic that is executed when using managed disks. This logic leads to an error and cancels resource removal.
Issue:
https://github.com/rancher/rancher/issues/22100
> Disable vhd delete when using managed disks

- Gopkg.lock
- drivers/vmwarevsphere/create.go
- drivers/vmwarevsphere/flags.go
- drivers/vmwarevsphere/utils.go
- drivers/vmwarevsphere/vm.go
- drivers/vmwarevsphere/vsphere.go
- vendor/github.com/vmware/govmomi/vapi/tags/categories.go
- vendor/github.com/vmware/govmomi/vapi/tags/tag_association.go
- vendor/github.com/vmware/govmomi/vapi/tags/tags.go
Adds two new flags to vmwarevsphere to allow passing of tags and custom attributes to be assigned to the newly created VM.
* Tags need to be  the full Tag ID, see `govc tags.info <tag>` to get the full urn.
* Custom Attributes need the Key name and a value in the format of "<int key>/<string value>". For instance if you do `govc fields.ls` to find the Key. Only accepts VirtualMachine type custom attributes.
```--vmwarevsphere-tag urn:vmomi:InventoryServiceTag:ee4de041-48d8-4709-b5a5-d08add628c75:GLOBAL \
--vmwarevsphere-tag urn:vmomi:InventoryServiceTag:be5f9250-9b71-4a2d-b0f0-5de8a9edfca6:GLOBAL \
--vmwarevsphere-tag urn:vmomi:InventoryServiceTag:d00f1cf2-6822-46a0-9602-679ea56efd57:GLOBAL \
--vmwarevsphere-custom-attribute '203/Team xyz field value' \```
> Adding Tags and Custom Attributes

- drivers/vmwarevsphere/cloudinit.go
- drivers/vmwarevsphere/create.go
- drivers/vmwarevsphere/flags.go
- drivers/vmwarevsphere/utils.go
- drivers/vmwarevsphere/vm.go
- drivers/vmwarevsphere/vsphere.go
Adds `--vmwarevsphere-datastore-cluster` flag to `vmwarevsphere` driver. This is a string to pass to the finder queries to find a datastore cluster to use during vm creation. VMs will boot and attach themselves to a datastore in the clusterbased on the return from the vsphere datastore recommendation api.
> Update vmwarevsphere Driver to Support datastore-clusters

- libmachine/provision/rancheros.go
Related Issue:
https://github.com/rancher/os/issues/2808
> Set RancherOS default docker storageDriver to overlay2

- drivers/vmwarevsphere/vm.go
VMs in the UI come with a full vsphere path and this folder concat isn't necessary any more and is breaking deployments which select folders.
> Removing Folder Concat

- drivers/vmwarevsphere/create.go
- drivers/vmwarevsphere/vm.go
disk size parameters were being ignored during the cloning process. This adds a check after cloning a VM to resize the disk on the fly.
> [vmwarevsphere] Add Disk Resizing to Cloning

- drivers/vmwarevsphere/create.go
- drivers/vmwarevsphere/flags.go
- drivers/vmwarevsphere/utils.go
- drivers/vmwarevsphere/vsphere.go
Fixing folders to work with deeper folder structures exposed a this old logic from the driver which prefixed folders when we are now passing in fully pathed folders. Leaving old system as a fall back for old nodetemplates.
https://github.com/rancher/rancher/issues/24840
> Adding Prefix Checks to Folder Find Logic

- drivers/amazonec2/amazonec2.go
- drivers/amazonec2/amazonec2_test.go
- drivers/amazonec2/stub_test.go
This PR adds a field to the AWS EC2 driver to request for encryption (using the AWS Managed Customer Master Key for EBS) on a volume-backed instance in EC2. It also pushes misc. fixes to the tests to allow them to pass `go test`.
Note: removed TestConfigureSecurityGroupPermissionsWithSwarm as Rancher no longer supports 'is swarm' default ports
https://github.com/rancher/rancher/issues/22691
> Add flag for encrypted ELB volume backed instances

- drivers/amazonec2/amazonec2.go
Problem:
Machine breaks during provisioning if attempting to use an existing
key-pair and a public key is not present locally.
Solution:
Move logic for copy public key. Now, machine should only attempt
to copy the public key if key-pair does not exist.
Dependency for:
https://github.com/rmweir/rancher/pull/9
> Remove copy public key

- contrib/completion/zsh/_docker-machine
- libmachine/provision/redhat.go
- libmachine/provision/redhat_test.go
Upgrades redhat to overlay2 per this docker/machine PR: https://github.com/docker/machine/pull/4560/files
https://github.com/rancher/rancher/issues/18065
> change default storage driver for redhat

- drivers/azure/azure.go
- drivers/azure/azureutil/azureutil.go
- drivers/azure/azureutil/cleanup.go
- drivers/azure/util.go
This PR allows users of the Azure driver to submit an NSG name or ARM resource identifier to be used by multiple machines that are provisioned via Rancher Machine. If a user does not submit an NSG name, machine will default to the legacy option of creating an NSG per machine.
> Enable NSGs shared between multiple machines

- drivers/azure/azure.go
- drivers/azure/azureutil/azureutil.go
Reverts a change added as part of https://github.com/rancher/machine/pull/72 to fail on PreCreateCheck if the OS disk already exists and adds in the ability to delete unused managed disks that were previously attached to Rancher VMs.
Related issue: https://github.com/rancher/rancher/issues/27316
> Add ability to delete unused managed disks on Azure

- drivers/azure/azure.go
- drivers/azure/azureutil/clients.go
This PR rolls back a change that was added in as part of https://github.com/rancher/machine/commit/b13f35b91cacbc867e7a0fb584ae65dffc3bb1aa#diff-93a074128ed8940ea0dafbd000270978R349.
`RegisterResourceProviders` makes a call to Azure to ensure that the current Azure subscription has the ability to deploy a resource for a given [resource provider](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types). Rancher does not require the ability to deploy a new subscription, so registering the Microsoft.Subscriptions resource provider is unnecessary. However, creating a resource group (Microsoft.Resources), a storage account (Microsoft.Storage), a network security group (Microsoft.Network), and a Virtual Machine (Microsoft.Compute) should still be …
> Remove register Microsoft.Subscription from Azure

- drivers/azure/azure.go
Related to a bug introduced in https://github.com/rancher/machine/pull/77, detailed in the issue.
Related Issue: https://github.com/rancher/rancher/issues/27468
> Relocate resolveNSGReference in Azure node driver

- drivers/vmwarevsphere/cloudinit.go
The cloud-init `meta-data` file is in YAML format. The leading asterisk commented out the `local-hostname` option so that the hostname was never applied to the machine by cloud-init.
See https://github.com/rancher/rancher/issues/27846
> Fix cloud-init hostname configuration for vSphere integration

- drivers/vmwarevsphere/create.go
The driver should inherit the GuestId (OS type) from the parent VM or template.  This avoids unexpected warnings when, for example, the VMware Paravirtual SCSI controller is selected.
> [vSphere] Don't override GuestId for VMs created from a template

- drivers/amazonec2/amazonec2.go
The default behavior for the ec2 machine driver is to allow encryption of ebs volumes.
This defaults to using the aws/ebs key.
Customer is looking for an option to specify customer managed keys for encryption/decryption of the ebs volume.
The minor tweak in this PR allows the user to specify the same.
Related to: https://github.com/rancher/rancher/issues/27015
> Allow Customer Managed encryption key for ec2 driver

- drivers/vmwarevsphere/vm.go
Datastores can contain spaces which can cause issues such as https://github.com/rancher/rancher/issues/27699
> use "]" instead of " " to split the VM folder name from the datastore

- libmachine/provision/fedora.go
- libmachine/provision/fedora_coreos.go
This adds support for Fedora CoreOS. Currently, Fedora CoreOS VMs are detected as Fedora, but the Fedora provisioner does not work because FCOS does not have `yum`.
This commit is inspired by upstream PR https://github.com/docker/machine/pull/4808.
> Add support for Fedora CoreOS

- drivers/amazonec2/amazonec2.go
- drivers/amazonec2/amazonec2_test.go
- drivers/amazonec2/ec2client.go
- drivers/amazonec2/stub_test.go
Currently, in order to deploy an AWS EC2 instance where root device name is not /dev/sda1 (e.g. official Fedora CoreOS AMIs use /dev/xvda), you have to specify the flag --amazonec2-device-name=/dev/xvda.
However:
1. Rancher UI does not allow setting easily this value in AWS EC2 node templates;
2. As [documented by AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html),    the root device name is specified in the AMI, so the best is to get the information automatically from the AMI.
Therefore, this commit removes the default option for --amazonec2-device-name, and if a value is not specified, it uses the root device name specified in the AMI.
> AWS driver: Detect root device name from AMI

- libmachine/provision/amazonlinux.go
The PR adds support for amazonlinux 2 provisioner which is based off the default SystemdProvisioner.
This should allow rancher-machine and Rancher to now launch RKE clusters using amazonlinux 2 ami's.
> Added support for provisioning amazon linux 2 based instances

- libmachine/provision/debian.go
- libmachine/provision/redhat.go
- libmachine/provision/suse.go
- libmachine/provision/ubuntu_systemd.go
- libmachine/provision/ubuntu_upstart.go
- libmachine/provision/utils.go
Issue: https://github.com/rancher/rancher/issues/27646
~~As discussed, removed the docker installation step during provision. The expectation now is the user has already pre-installed everything they need to have installed docker themselves (will need to be documented).~~
Edit:
Updated provisioning to allow users to opt-in for skipping docker install by passing in `"none"` as the `engineInstallURL`, which can be easily added to the UI's dropdown of docker installation options. 
Users will now have the following options:
1. Provide no URL => Defaults to installing docker using default URL (get.docker.com)
2. Provide a URL => URL is used to install docker
3. Provide `"none"` as the URL => installing docker will be skipped
> [master] Allow skipping docker installation

- drivers/amazonec2/amazonec2.go
Encrypted AMI's which have multiple ebs volumes do not have the KMS key applied to volumes other than the root disk.
The PR introduces an additional bool flag `--amazonec2-encrypt-additional-volumes`.
This will query the AMI for additional EBS volumes and apply the encryption settings to these too as part of the instance launch.
> Additional flag to encrypt all ebs volumes associated with ami

- drivers/vmwarevsphere/vsphere.go
- libmachine/drivers/utils.go
Problem: 
vsphere can have multiple IP addresses on the hose, some of those which are not reachable from the outside. In those cases if that IP ends up first in the list machine won't be able to connect. 
Solution:
Loop over the list of IP addresses and attempt to ssh into the node to ensure a connection can be made.
> Attempt ssh

- libmachine/provision/suse.go
Related to https://github.com/rancher/rancher/issues/30717
Changes in logic to query if SuSEfirewall (SLES12) or firewalld(SLES15) is installed.
Current logic assumes if firewalld is not installed then SuSEfirewall is available and then tries to configure instance using SuseFirewall.
This causes instance provisioning to fail.
The firewall configuration logic has been fine tuned to make it more explicit and only add firewalld rules if firewalld is installed and running.
This helps cover use cases where firewalld is not available as well, and driver now no longer defaults to SuSEfirewall.
> SLES15 firewalld support

- libmachine/provision/suse.go
The current OS detection code looks for openSUSE only, which no longer works given the split between Leap and Tumbleweed.
Update the relevant strings so that the driver successfully detects and provisions a cluster on all openSUSE variants.
Tested against openSUSE Leap 15.2 with an image built using [this Packer template](https://github.com/yankcrime/Rancher-Packer/tree/opensuse_leap_15.2/vSphere/opensuse_leap_15.2) and vSphere 7.0.1.
> Support openSUSE variants

- drivers/amazonec2/region.go
**Problem:**
AMIs are outdated.
**Solution:**
Update them with AMIs from https://cloud-images.ubuntu.com/locator/ec2/. Use filters: version- 20.04 LTS, arch- amd64, and region. Moved to 20.04 because 16.04 will be deprecated soon.
**Issue:**
https://github.com/rancher/rancher/issues/31708
> Update defaults AMIs for AWS

- drivers/google/google.go
The changes to add userdate to the Google driver mistakenly always tried
to read the userdata file. Now, the driver will only look for the
userdata file when one is passed to the driver.
> Stop looking for blank google userdata file

- drivers/vmwarevsphere/create.go
Ref: https://github.com/rancher/rancher/issues/31407
```
Problem: VMs deployed via the content library will always land in the root folder instead of the custom folder passed by driver.
Root cause:  createFromLibraryName() uses d.datacenter.Folders(d.getCtx()) which won't return the proper folder path.
Fix: A PR was pushed in the past https://github.com/rancher/machine/pull/61 , but this was not included in createFromLibraryName() 
```
Ref: https://github.com/rancher/rancher/issues/31408
```
Problem: VMs deployed via content library will not map network interfaces properly 
Root cause:  FilterLibraryItem - https://pkg.go.dev/github.com/vmware/govmomi/vapi/vcenter#Manager.FilterLibraryItem was missing in the code path which resulted in ignoring network assignments 
Fix: The OVF template …
```
> VM folder path and network assignment fix

- package/entrypoint.sh
If the rancher-machine image is run in a pod, then the exit code of the
pod was not being properly set if the rancher-machine call failed (set
to 0 even though rancher-machine exited with code 1). The changes to the
entrypoint script properly sets the exit code if the rancher-machine
command fails while still passing the ouput of the command to tee.
> Set proper exit code on pod exit

- drivers/openstack/client.go
The PR adds the availability_zone parameter to the VolumeCreate function if the parameter is not empty.
https://github.com/rancher/rancher/issues/32775
> add AvailabilityZone param to VolumeCreate opts

- drivers/azure/azure.go
- drivers/azure/azureutil/auth.go
- drivers/azure/util.go
The Azure driver currently uses an interesting way of getting the tenant ID from the subscription ID. A flag is added to allow a user or Rancher to pass the desired tenant ID to the driver.
Issue:
https://github.com/rancher/rancher/issues/31014
> Add tenant ID to Azure driver

- drivers/vmwarevsphere/create.go
Fixes https://github.com/rancher/rancher/issues/32761 
The VM gets deployed from the content library was taking defaults from
OVF template instead of driver input. Added code to reconfigure VM
based on the input from the driver.
> Fix cpu & memory change in content library

- scripts/build
The "-s" option is a ldflags option, not an -extldflags option.
This correctly strips the debug symbols and reduces binary size
by 20MB (25%)
> Fix typo in ldflags causing debug symbols to not be stripped

- go.mod
- go.sum
This change was causing rancher-machine to hang when provisioning vsphere
machines.
This reverts commit 71d51fd97c039fe39a1a52b9a973843c855ab3a9.
Issue:
https://github.com/rancher/rancher/issues/33783
> Revert "update govmomi version to v0.26.0"

- package/entrypoint.sh
The command line arguments to rancher-machine were being passes as `--driver=great_driver`. However, this did not allow for handling cases where the value had a space in it.
Now, by splitting the these up to `--driver` `great_driver`, we are able to quote the values, which allows for handling of spaces.
Issue:
https://github.com/rancher/rancher/issues/33867
> Handle spaces in commandline arguments

- libmachine/provision/custom_script.go
Previously, the method of running the custom install script on the
remote machine was faulty for anything besides a simple script. Now, the
file upload and the running of the script are done in two separate steps
to handle the more complicated script.
Issue:
https://github.com/rancher/rancher/issues/32371
> Add more robust custom script upload when using SSH

- libmachine/provision/custom_script.go
- package/Dockerfile
For some reason, the Go Native SSH implementation is not playing well
when run in Kubernetes. This change will install the ssh command into
the image so that the rancher-machine binary will use that instead.
Issue:
https://github.com/rancher/rancher/issues/33865
> Install ssh client in the docker image

- package/Dockerfile
There were changes in Rancher to run the rancher-machine container as a
non-root user. This caused some permissions errors. This change fixes
those permissions issues and sets the non-root user in the Dockerfile.
Related issue:
https://github.com/rancher/rancher/issues/34302
> Run container as non-root user

- drivers/openstack/client.go
- drivers/openstack/openstack.go
This PR fixes the issue that causes Openstack node creation to fail due to a race condition in the floating IP address handling. See https://github.com/rancher/rancher/issues/27864
Further discussion of the issue can be found here: https://github.com/docker/machine/issues/4038
Note that the code changes are entire limited to the Openstack driver package.
PR has been tested and fix validated using Rancher 2.5.9 and RH Openstack 16
> Fix: Openstack node provisioning fails with floating ip assignment

- drivers/azure/azure.go
- drivers/azure/azureutil/azureutil.go
Problem:  Creating a virtual machine from Marketplace image requires Plan information in the request.
Adds a new flag, in the `<publisher>:<product>:<plan>` format, to provide marketplace purchase plan information when provisioning Azure vms.
Issues: 
- rancher/rancher#27854
- rancher/rancher#22927
> Add image purchase plan to Azure driver

- commands/create.go
- drivers/digitalocean/digitalocean.go
In order to make the machine provisioning more consistent across the
multiple cloud providers, the name of the machine is passed to the
cloud-config as the hostname. Certain cloud providers (like Digital
Ocean) automatically set the hostname to the machine name, but others
(like AWS) do not.
A couple simplifications also accompany this PR.
Issue:
https://github.com/rancher/rancher/issues/35141
> Add hostname to cloud config

- .drone.yml
Added a ad-hoc git clone step for s390x step in order to solve the issue with git clone step. Which has been reported by @rosskirkpat after facing it running the following pipeline https://drone-pr.rancher.io/rancher/machine/319/3/1 
This issue also happened on [racher/rancher 
](https://github.com/rancher/rancher) and applied the fix https://github.com/rancher/rancher/blob/04f609f82de0e9c7dd4d01cede088de467c62d94/.drone.yml#L568
> Added ad-hoc git clone step for s390x

- libmachine/provision/rockylinux.go
Hello,
I added a new provisioner in the `libmachine` module so Rocky Linux 8 is supported by rancher-machine.
Here are the results of the tests that i've done on my side : 
Running `rancher-machine create` :
```
./rancher-machine create -d vmwarevsphere \
--vmwarevsphere-username XXXXXX \
--vmwarevsphere-password XXXXXX \
--vmwarevsphere-memory-size 4096 \
--vmwarevsphere-vcenter XXXXXX \
--vmwarevsphere-vcenter-port 443 \
--vmwarevsphere-disk-size 20000 \
--vmwarevsphere-clone-from "/XXXXXX/vm/Rancher/template/TEMPLATE_ROCKY8" \
--vmwarevsphere-cpu-count "4" \
--engine-install-url https://raw.githubusercontent.com/lukry59/install-docker/master/dist/20.10.12.sh \
--vmwarevsphere-datastore-cluster "/XXXXXX/datastore/Storage Class Gold (SSD)" \
--vmwarevsphere-creation-type "template" \ …
```
> Added Rocky Linux 8

- .gitignore
- commands/create.go
- drivers/amazonec2/amazonec2_test.go
- drivers/vmwarevsphere/cloudinit.go
- drivers/vmwarevsphere/create.go
- drivers/vmwarevsphere/flags.go
- drivers/vmwarevsphere/vm.go
- drivers/vmwarevsphere/vsphere.go
- libmachine/drivers/drivers.go
- libmachine/host/host.go
- libmachine/provision/fedora_coreos.go
The new `--vmwarevsphere-os` flag and it's value is only passed through when a driver has added support for it. The only driver that currently has support is the vmwarevsphere node driver.
The design behind this flag is that it's value should be set by Rancher and passed through to machine where it should only be consumed and not modified.
In the vsphere driver itself, there is now separate logic for linux and windows when it comes to correctly configuring cloud-init (the custom install script is `.sh` for linux and `.ps1` for windows) and also when adding users/groups via cloud-config (windows uses cloudbase-init which has a slightly different config structure/requirement).
linked issues:
https://github.com/rancher/windows/issues/18
> add OS support to vsphere

- Makefile
- package/Dockerfile
- package/entrypoint.sh
The machine pod was not able to trust the Rancher certificates passed to the job
for downloading the drivers. This change will run c_rehash when the machine pod
starts up to allow the curl commands to work.
In addition to using the c_rehash command, the base image is changed to SLE BCI to
be consistent with Rancher.
Issue:
https://github.com/rancher/rancher/issues/36488
> Allow machine to trust Rancher certs

- commands/create.go
- drivers/vmwarevsphere/cloudinit.go
- drivers/vmwarevsphere/flags.go
- go.mod
- go.sum
- package/Dockerfile
changes:
- add mkisofs to machine image and use it for linux+windows iso creation (adding Joliet support for Windows)
- remove project dependency on godisk-fs
- go mod tidy
- fix bug in how the `vmwarevsphere-os` flag is validated during machine creation
fix for 
https://github.com/rancher/windows/issues/155
https://github.com/cloudbase/cloudbase-init/issues/89
https://github.com/rancher/rancher/issues/36653
> use mkisofs to create joliet and rockridge isos

- drivers/vmwarevsphere/cloudinit.go
- drivers/vmwarevsphere/vsphere.go
Original panic:
```console
[ERROR] error syncing 'c-lgdkp/m-g2ct4': handler node-controller: Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: invalid memory address or nil pointer dereference, requeuing
```
This panic was a multi-faceted problem:
- mkisofs not existing in a rancher jail for rke1 vsphere clusters (https://github.com/rancher/rancher/pull/36850)
- mkisofs not being in the proper path for rancher (needs to be `/usr/bin/mkisofs` inside the jail, https://github.com/rancher/rancher/pull/36927)
- mkisofs exec.command needed a path set for it to function inside the jail
> fix mkisofs in a jail, check more nils

- drivers/amazonec2/amazonec2.go
This PR addresses https://github.com/rancher/rancher/issues/36958. The EC2 driver has been modified to apply tags to several of the resources created during the instantiation an EC2 instance. Most notably, the EBS volume and Network interface.
If there are other resources that should be tagged, let me know. From looking at the EC2 instance panel in the AWS console it appears that an EBS volume and Network interface are created on demand, but I couldn't identify any other resources created or managed by Rancher when spinning up an EC2 instance.
> Apply tags to resources created for EC2 instances.

- libmachine/cert/cert.go
- libmachine/ssh/client.go
- libmachine/util/util.go
Issue: https://github.com/rancher/rancher/issues/37295 
The `rancher-machine` is used to create nodes when we create a node-driver cluster, but it does not use the `NO_PROXY` env variable, so when the proxy cannot talk to the node in the downstream cluster, or the proxy server uses self-signed certs, rancher-machine will not be able to ssh to the node. 
With this fix, rancher-machine will check the NO_PROXY environment variable along with HTTP_PROXY and HTTPS_PROXY to determine if the proxy should be used when it tries to ssh into or validate the certs on the node.
The builtin `ProxyFromEnvironment` function does the check for us:  https://pkg.go.dev/net/http#ProxyFromEnvironment
Prepare the setup:
- run an EC2 instance that has public IP and internet access,  run squid proxy server, the …
> Use the NO_PROXY environment variable

- drivers/amazonec2/amazonec2.go
- drivers/amazonec2/amazonec2_test.go
- scripts/ci
- scripts/test
Enabled the existing tests for the drivers that we ship in Rancher.
* https://github.com/rancher/windows/issues/143
> Enabling go tests for drivers that ship in Rancher

- drivers/amazonec2/amazonec2.go
Issue: https://github.com/rancher/rancher/issues/38422
This PR ensures that error messages encountered during the creation of EC2 instances are logged properly. `go fmt` has also been run to fix formatting errors of previous PR's.
> ensure proper logging of instance creation failures

- commands/create.go
- drivers/vmwarevsphere/cloudinit.go
- addresses a bug with the vsphere driver where `meta-data` files for the NoCloud datasource was using `hostname` instead of `local-hostname`.
- add additional comments to clarify some of the linux/windows specific logic
- set the hostname based on OS as cloud-init (linux) and cloudbase-init (windows) diverge on how hostnames are set in cloud-config (userdata)
Fixes https://github.com/rancher/rancher/issues/37412
SURE-4636
> use local-hostname for meta-data and update windows logic

- drivers/azure/azureutil/cleanup.go
Issue: https://github.com/rancher/rancher/issues/35055
It appears that Azure Availability Sets are not being cleaned up properly when deleting a rancher provisioned instance. All Azure resources are checked to determine if independently created resources are utilizing rancher-managed resources which are queued for deletion. This ensures that other projects utilizing resources created by Rancher are not impacted when cleaning up a Rancher created instance. In the case of Availability Sets, this check was incorrectly written with an `AND` operator as opposed to an `OR` operator. This was causing the conditional to fast-fail, as the `VirtualMachines` slice is never `nil` (but is empty), resulting in machine always thinking that the Availability Set was not safe for deletion. 
Note: This is …
> Ensure azure Availability-Sets are cleaned up

- drivers/azure/azure.go
- drivers/azure/azureutil/azureutil.go
Issues: https://github.com/rancher/rancher/issues/26955 https://github.com/rancher/rancher/issues/37847  https://github.com/rancher/rancher/issues/39458
This PR adds flags and support within rancher-machine for several Azure features. This includes 
+ adding tags to Azure VM's created by rancher-machine
+ specifying if Azure NIC's should use Accelerated Networking
+ Supporting the specification of Availability Zones when creating VM's. 
This PR is being raised as the individually created PR's raised previously will result in merge conflicts, having them all in a single PR is cleaner. 
I've manually compiled and run the rancher-machine binary and confirmed that the provided tags are applied to the VM instance.
Currently UI support is not implemented for this feature. To test this you …
> [v2.7.1] Add flags for multiple Azure features

- drivers/azure/azure.go
This issue was found during UI implementation of the Azure accelerated networking feature. 
This PR adds registers the new `azure-accelerated-networking` flag to the `mcnflag` set, which was missed during the prior PR. This is required for the new flag to show up when running `rancher-machine create -d azure --help` as well as for the Rancher schema to be updated properly. Basically, this PR advertises this flag as opposed to simply accepting it. 
Run `rancher-machine create -d azure --help` and confirm the new flag is included in the output
When Rancher machine is bumped in rancher/rancher you should be able to confirm this new flag by visiting 
`https://RANCHER_SERVER/v1/schemas/rke-machine-config.cattle.io.azureconfig`
> [v2.7] Add missing Accelerated Networking flag to mcnflag set

- libmachine/log/fmt_machine_logger.go
Fix compatibility with gitlab-runner's docker+machine executor. Writing to stdout causes rancher-machine's output to be not parsable.
See https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27026#note_474771460
Issue: https://github.com/rancher/rancher/issues/40975
> Write debug logs to stderr

- commands/create.go
- libmachine/host/host.go
- libmachine/libmachine.go
- libmachine/provision/custom_script.go
https://github.com/rancher/rancher/issues/40901
Added `--hostname-override` flag to create, since hostname is set at the machine level and not on a per-provider basis. I'm still working on the implementation for non `custom-install-script` (i.e. vanilla machine provisioning i.e RKE1), but this should be enough to review for the minimum viable product.
> Add hostname override flag to create

- libmachine/log/fmt_machine_logger.go
Reverts rancher/machine#203
This causes problems with the Rancher integration that is not expecting debug logs on stderr.
> Revert "Write debug logs to stderr"

- drivers/google/compute_util.go
Issue: [rancher/rancher#42586](https://github.com/rancher/rancher/issues/42586)
When user data is provided, docker-machine overwrites `metadata.Items` with user-data key, so ssh-keys are not created. This PR fixes the issue. Now, if user data is provided, the key is appended instead of overwriting ssh-keys metadata.
I have tested using the following command 
```
./bin/rancher-machine create --driver google \
--google-project <project-id> \
--google-zone us-central1-a \
--google-machine-type n1-standard-2 \
--google-machine-image ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230714 \
--google-userdata userdata.sh\
rancher-vm
```
GCP machine is created successfully with the given userdata.
> Fix User-data pass in GCP Machine

- drivers/vmwarevsphere/flags.go
- drivers/vmwarevsphere/vsphere.go
https://github.com/rancher/rancher/issues/42308
Please have a look at the internal design doc for details. 
This PR has been tested by compiling and using rancher-machine locally. If we crate a machine with the vmwarevsphere driver and set the `vmwarevsphere-graceful-shutdown-timeout` flag, for example 
```
./rancher-machine create -d vmwarevsphere  .. ... --vmwarevsphere-graceful-shutdown-timeout 100  jiaqi-vsphere-t1
```
Then, when we remove this machine by running `./rancher-machine remove  jiaqi-vsphere-t2`,  we can confirm the feature is working by seeing the following:
- relevant messages in the output 
- In vSphere Center Client, the task "initial guest os shutdow' is triggered, which does not happen if we do not set the flag. 
After this PR is merged I am going to cut a new tag …
> add the support for vmwarevsphere graceful shutdown

- drivers/amazonec2/amazonec2.go
- drivers/azure/azure.go
- drivers/digitalocean/digitalocean.go
- drivers/exoscale/exoscale.go
- drivers/google/google.go
- drivers/noop/driver.go
- drivers/openstack/openstack.go
- drivers/rackspace/rackspace.go
- drivers/softlayer/driver.go
- drivers/vmwarefusion/fusion_darwin.go
- drivers/vmwarevcloudair/vcloudair.go
- drivers/vmwarevsphere/flags.go
This PR addresses https://github.com/rancher/rancher/issues/42972, which is caused by the change in https://github.com/rancher/machine/pull/224 that was supposed to address https://github.com/rancher/rancher/issues/40608.
The `UnmarshalJSON` function on the `amazonec2` driver was causing the driver to panic. Here's an explanation in the form of code comments:
**drivers/amazonec2/amazonec2.go**
```go
func (d *Driver) UnmarshalJSON(data []byte) error {
// Unmarshal driver config into an aliased type to prevent infinite recursion on UnmarshalJSON.
type targetDriver Driver
// This essentially creates a new `Driver` where all fields have zero values. The problem is
// that this `amazonec2.Driver` struct type has fields that are functions that are set in
// `NewDriver`. With this struct …
```
> Fix dropped values during driver unmarshal

- drivers/amazonec2/amazonec2_test.go
- drivers/azure/azure_test.go
- drivers/digitalocean/digitalocean_test.go
- drivers/exoscale/exoscale_test.go
- drivers/google/google_test.go
- drivers/openstack/openstack_test.go
- drivers/rackspace/rackspace_test.go
- drivers/softlayer/driver_test.go
- drivers/vmwarefusion/fusion_darwin.go
- drivers/vmwarefusion/fusion_darwin_test.go
- drivers/vmwarevcloudair/vcloudair.go
- drivers/vmwarevcloudair/vcloudlair_test.go
- drivers/vmwarevsphere/flags.go
- drivers/vmwarevsphere/vsphere_test.go
- scripts/test
Follow up from https://github.com/rancher/machine/pull/227 (for https://github.com/rancher/rancher/issues/42972)
- Fix bug where we access the wrong key in vSphere config for the username
- Added unit tests for custom `UnmarshalJSON` implementation on drivers.
- Fixed `UnmarshalJSON` for Fusion and VCloud Air drivers. The bug where turns out to have no effect because all fields in those drivers are marshalled and unmarshalled (i.e. there are no weird function or pointer fields).
- Update CI to run all driver unit tests
> Fix vSphere username rotation / add unit tests for `UnmarshalJSON`

- libmachine/provision/redhat.go
fix: Redhat reboot only required when NM services are disabled. (source: https://github.com/rancher/machine/pull/226)
https://github.com/rancher/rancher/issues/43119
> [v0.15.0-rancher100-patch1] fix: Redhat reboot only required when NM services are disabled.  

- libmachine/provision/suse.go
issue: https://github.com/rancher/rancher/issues/43254
overlay storage driver is removed in docker v24.0 [ref](https://docs.docker.com/engine/deprecated/#:~:text=Legacy%20overlay%20storage%20driver&text=The%20overlay%20storage%20driver%20is,0.)
> update default storage driver to overlay2 for suse os

- libmachine/provision/ubuntu_systemd.go
- libmachine/provision/utils.go
Original Issue: https://github.com/rancher/terraform-provider-rancher2/issues/1215
Actual Issue: https://github.com/rancher/rancher/issues/43586
The problem appears to be that with ubuntu 22.04 there is either a lot more going on at startup or in the cloud-init that installing docker _immediately_ after the ssh daemon is up can cause any subsequent `apt` commands to be flakey. 
Notable failures include:
- `apt-get update` failing to pull down repo lists
- `curl <install-docker.sh> | sh -` failing to install docker with a _very_ helpful `Error installing Docker: ` error message
The fix is just to wait for cloud-init to be completed when starting the machine-provision process.
---
I tested this with ubuntu 20.04 and ubuntu 22.04 which were the only supported dpkg distros in the UI for DO. …
> Wait for cloud-init to complete before continuing provision

- libmachine/provision/redhat.go
This PR includes 
- everything in https://github.com/rancher/machine/pull/226 
- some improvement on the debug messages, which was requested but not addressed on the original PR ([commit](https://github.com/rancher/machine/pull/226#discussion_r1428459152)). 
The following is done to dev-validate the additional changes to the Bash command:
- run a RHEL VM on AWS:
```
>  cat /etc/redhat-release
Red Hat Enterprise Linux release 8.6 (Ootpa)
```
- validation 1: copy and run the following command from the code:
```
> if [ -f /tmp/rancher-machine-reboot ]; then echo NetworkManager is patched, waiting for machine to reboot && rm -f /tmp/rancher-machine-reboot && sudo reboot; else echo NetworkManager has been disabled, nothing to do; fi
NetworkManager has been disabled, nothing to do
> echo $?
0 …
```
> fix: Redhat reboot only required when NM services are disabled

- libmachine/crashreport/crash_report.go
The original config of docker-machine used to send errors  to bugsnag, this config was enabled by default both on docker-machine and rancher-machine. 
The user had to express that data sholdn't be sent using: `MACHINE_BUGSNAG_API_TOKEN=no-report` what wasn't intuitive.
As we do not have have access to those logs the idea was to default the value to not sending logs, with this changes if no ENV is passed no logs will be send to bugsnag. 
It also allows the user to keep the current default behavior by setting: `MACHINE_BUGSNAG_API_TOKEN=docker-machine-default`. 
*  Enabled debug mode on machine (envs on rancher) 
*  On rancher went to the create cluster (EC2). 
*  Removed my IAM permission to create EC2 (I had to do this after setting the cluster config)
*  Create Cluster.
*  Check machine …
> Remove default crash reporter

- package/Dockerfile
rancher images currently being built no longer run due to the missing package openssh-clients. rancher-machine  when running and causes rancher-macine to have issue in some case if it does not exist.
The package is missing since git-core which was being installed by rancher no longer requires openssh-clients.
Root causes of this issue are rancher-machine container does not explicitly install openssh-clients.
This PR fix the issue by specifically installing the ssh client
> re-add ssh client to rancher-machine container

- package/Dockerfile
Bump the base image to `bci-base:15.5`, which is a more recent version than `bci-base:15.4` and fix some low hanging CVEs in base OS packages.
> Bump base image to `bci-base:15.5`

- libmachine/drivers/utils.go
Just made a small update to the `WaitForSSH` function so it doesn't swallow errors.
> Update SSH retry so it doesn't swallow errors

- drivers/vmwarevsphere/create.go
- drivers/vmwarevsphere/vsphere.go
- libmachine/libmachine.go
**Issue**
https://github.com/rancher/rancher/issues/44212 
Possibly: https://github.com/rancher/rancher/issues/46340
**Problem**
In general, rancher-machine takes at least three steps to provision a vSphere machine: first, create the VM instance; then customize the VM's configuration; and finally bootstrap the VM.
Previously, rancher-machine saves the VM's ID only after the bootstrapping step succeeds. If rancher-machine creates but fails to start the VM, it will not destroy the VM because the VM's uuid is missing.
**Solution**
Now, rancher-machine retrieves and saves the uuid as machineID as soon as the VM is created, and saves the updated Host object to the store even if the creation process fails. This ensures the machineID is always preserved so that rancher-machine can find and …
> Fix the issue where rancher-machine does not clean up vSphere VMs that are in failed status

- Dockerfile.dapper
- go.mod
https://github.com/rancher/rancher/issues/46517
https://github.com/rancher/rancher/issues/46516
https://github.com/rancher/rancher/issues/46515
Changes:
- bump golang toolchain to go1.22.5
- bump base image to bci/golang:1.22 for Dapper
> Bump Go versions to 1.22 

- go.mod
isssue: https://github.com/rancher/rancher/issues/47678
> bump go version to 1.22.8

- package/Dockerfile
https://github.com/rancher/rancher/issues/47853
This reverts commit 3d1d808b6703079fe78bd7214db059f41e71c20b.
#252 introduced a change which resulted in failures to download external node drivers, receiving the following message:
```
Downloading driver from ...
Doing /etc/rancher/ssl
ls: docker-machine-driver-*: No such file or directory
downloaded file  failed sha256 checksum
download of driver from ... failed
```
The Rancher CAs are mounted into the pod, and the following is performed in order to use the CAs: https://github.com/rancher/machine/blob/master/package/download_driver.sh#L5-L13
> [47853] Downloading node drivers no longer works

- package/Dockerfile
https://github.com/rancher/rancher/issues/46100
**This PR includes:**
- All changes from https://github.com/rancher/machine/pull/252
- The fix for the permissions issue that causes node driver downloads to fail. [issue](https://github.com/rancher/rancher/issues/47853) 
**More information about the node-driver-downloading issue:**
When provisioning an RKE2/K3s node-driver cluster in Rancher, Rancher deploys a Job that runs the `rancher-machine` container. This container first downloads the external node driver, then invokes the `rancher-machine` binary to create the VM in the cloud ([code](https://github.com/rancher/machine/blob/master/package/entrypoint.sh#L28-L39)). The container runs with a security context configured as `runAsUser: 1000` and `runAsGroup: 1000`. In the original PR, the …
> Re-add "Change the generated image to `bci-busybox:15.6` (#252)" with additional fixes

- libmachine/provision/redhat.go
needed to keep openssh and openssl versions in sync
issue: https://github.com/rancher/rancher/issues/48143 / https://github.com/rancher/rancher/issues/48193
problem: curl is installed before installing docker and curl installation on rhel was causing openssl to autoupgrade. 
```
$ sudo -E yum install -y curl
Transaction Summary
=========================================================================================================================================================
Install  2 Packages
Upgrade  4 Packages
Total download size: 4.6 M
Downloading Packages:
(1/6): openssl-fips-provider-3.0.7-6.el9_5.x86_64.rpm                                                                    186 kB/s | 9.4 kB     00:00    
(2/6): curl-7.76.1-31.el9.x86_64.rpm …
```
> [RKE] [RHEL]: install openssl and openssh with curl

- scripts/build
Fix `scripts/build` (triggered by `make build CROSS=1`) on Darwin to produce correctly both arm64 and x86_64 binaries:
- fix build of `rancher-machine-Darwin-x86_64` to use GOARCH=amd64 even when building from arm64
- add `rancher-machine-Darwin-arm64`
> chore: fix scripts/build for Darwin targets

- .github/workflows/fossa.yaml
Just a tiny fix to the workflow syntax here. The `workflow_dispatch` trigger is nested one level too far, so it's not actually valid this way.
> fix nesting for GHA workflow trigger

- drivers/google/compute_util.go
- drivers/google/compute_util_test.go
When provisioning GCE node driver clusters which have several machines (3+) in a given pool, the machine provisioning jobs may encounter a transient error when attempting to create internal or external firewall rules. This is due to a race condition between multiple provisioning jobs attempting to create a firewall rule using the same name at the same time.
rancher-machine is expected to first detect if a rule exists and use it if it does. In this case, the rule is being created by one pod in the short amount of time between the initial check and the creation attempt within another pod.
This error does not prevent GCE clusters from being provisioned successfully, but does result in some churn in the machine provision pods and GCE VM instances. 
Do not return an error and use the existing …
> Properly handle existing GCP firewall rules
